name: CI (root)

on:
  push:
    branches:
      - "root"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4

        with:
          java-version: 17
          distribution: temurin

      - name: Set up Kotlin
        uses: fwilhe2/setup-kotlin@main

      - name: Set up Gradle properties

        run: |
          mkdir -p ~/.gradle
          echo "githubToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.gradle/gradle.properties
          echo -e "\norg.gradle.jvmargs=-XX:MaxMetaspaceSize=5G" >> ~/.gradle/gradle.properties

      - name: Gradle (Setup)
        uses: gradle/actions/setup-gradle@v3

        env:
          TOKEN: "${{ secrets.TOKEN }}"

        with:
          dependency-graph: generate-and-submit

      - name: Gradle (Build)
        run: "./gradlew checkLicenses build publishToMavenLocal"

        env:
          TOKEN: "${{ secrets.TOKEN }}"

      - name: Gradle (Test)
        run: "./gradlew build"
        working-directory: "./testModule"

        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Upload plugin JARs
        uses: actions/upload-artifact@v4

        with:
          name: Plugin JARs
          path: "*/build/libs/*.jar"
